#
# Autogenerated by Thrift Compiler (0.16.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
from thrift.TRecursive import fix_spec

import sys
from .ttypes import *
ErrMsg = {
    4: "异常",
    2: "不合法参数",
    1: "未知错误",
    0: "成功",
    3: "超时",
    100: "内存不足",
    101: "未初始化",
    102: "机器未注册",
    103: "无可用的资源",
}
