QuSprout: # http://qusprout.queco.cn for prod
  schema: http
  host: 192.168.170.195
  port: 9093
  api:
    common: /request

QuSaas: # http://developer.queco.cn for prod
  schema: http
  host: 192.168.166.110
  port: 9998
  api:
    token: /oauth2/token/
    # gateway: /gateway/qusprout/

QuPot:
  schema: http
  host: 192.168.170.202
  port: 40001
  api:
    common: /request
