#
# Autogenerated by Thrift Compiler (0.15.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
from thrift.TRecursive import fix_spec

import sys
from .ttypes import *
ErrMsg = {
    4: "exception",
    2: "invalid parameter",
    6: "existence",
    7: "be queuing",
    8: "out of memory",
    5: "non-existence",
    9: "uninitialized",
    10: "unregistered",
    11: "out of resource",
    1: "unknown error",
    12: "parse error",
    0: "success",
    3: "timeout",
}
